### ISSUE TITLE
Não é possível completar o 7º passo do README

### ISSUE THREAD

**Issue by wendellpbarreto** [topicos20152/API#20]
<img width="1440" alt="screenshot 2015-10-21 12 48 25" src="https://cloud.githubusercontent.com/assets/2782873/10641993/22516c60-77f2-11e5-8528-213e43a3da8d.png">

**Comment by adelinosegundo** [comment]
Esse erro é devido a falta do Mongo, foi adicionado ao README esse dependencia

**Comment by luanfonceca** [comment]
Vou fechar essa issue beleza?

**Comment by luanfonceca** [comment]
isso foi resolvido no pr #17
