### ISSUE TITLE
Create Task model

### ISSUE THREAD

**Issue by luanfonceca** [topicos20152/API#5]
Task
- status
- delivery_date
- title
- description
- attachment
- course:references

**Comment by adelinosegundo** [comment]
Acredito que o atributo "score" deve ficar um modelo entre User e Task

**Comment by luanfonceca** [comment]
@adelinosegundo nós teríamos então uma `TaskUser`? que é a M2M desses dois.

Ou seja, o `score` é a nota daquele aluno naquela atividade.

**Comment by adelinosegundo** [comment]
Vou fazer essa issue
